name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application on Ubuntu
        run: |
          cd "${{ secrets.PROJECT_PATH }}"
          git pull origin main
          npm install --production
          pm2 restart github-actions-ubuntu-deploy || pm2 start app.js --name github-actions-ubuntu-deploy
          pm2 save